# Default values for sidewinder.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

server:
  config:
    shardCount: 11
    tpchScale: 100
    pingTimeout: 300

  replicaCount: 1

  image:
    repository: 795371563663.dkr.ecr.us-east-2.amazonaws.com/sw
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  podSecurityContext:
    fsGroup: 1000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 8765

  resources:
    limits:
      cpu: 16
      memory: 64Gi
    requests:
      cpu: 16
      memory: 64Gi

  nodeSelector:
    alpha.eksctl.io/nodegroup-name: sw-cpu-node-group

  tolerations: []

  affinity: {}

worker:
  image:
    repository: 795371563663.dkr.ecr.us-east-2.amazonaws.com/sw
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 80

  resources:
    limits:
      cpu: 4
      memory: 16Gi
    requests:
      cpu: 4
      memory: 16Gi

  nodeSelector:
    alpha.eksctl.io/nodegroup-name: sw-cpu-node-group

  tolerations: []

  affinity: {}

client:
  replicaCount: 1

  image:
    repository: 795371563663.dkr.ecr.us-east-2.amazonaws.com/sw
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 80

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 1
      memory: 2Gi

  nodeSelector:
    alpha.eksctl.io/nodegroup-name: sw-cpu-node-group

  tolerations: []

  affinity: {}
