# Default values for sidewinder.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

server:
  config:
    databaseFile: data/ssb_sf1000.duckdb
    shardDataPath: s3://voltrondata-sidewinder/shards/ssb/sf=1000
    pingTimeout: 900

  replicaCount: 1

  image:
    repository: prmoorevoltron/sidewinder
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  podSecurityContext:
    fsGroup: 1000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 8765

  resources:
    limits:
      cpu: 60
      memory: 235Gi
    requests:
      cpu: 60
      memory: 235Gi

  nodeSelector:
    alpha.eksctl.io/nodegroup-name: graviton-3-cpu-node-group

  tolerations:
    - key: sidewinder
      operator: Equal
      value: "true"
      effect: NoSchedule

  affinity: {}

worker:
  config:
    tlsVerify: False

  image:
    repository: prmoorevoltron/sidewinder
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 80

  resources:
    limits:
      cpu: 4
      memory: 16Gi
    requests:
      cpu: 4
      memory: 16Gi

  nodeSelector:
    alpha.eksctl.io/nodegroup-name: graviton-3-cpu-node-group

  tolerations:
    - key: sidewinder
      operator: Equal
      value: "true"
      effect: NoSchedule

  affinity: {}

client:
  config:
    tlsVerify: False

  replicaCount: 1

  image:
    repository: prmoorevoltron/sidewinder
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 80

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 1
      memory: 2Gi

  nodeSelector:
    alpha.eksctl.io/nodegroup-name: graviton-3-cpu-node-group

  tolerations:
    - key: sidewinder
      operator: Equal
      value: "true"
      effect: NoSchedule

  affinity: {}
