tables:
  - name: orders
    parent_table_name: ''
    query_template: |-
      SELECT CAST ({shard_id} AS INTEGER) AS shard_id
           , orders.* 
        FROM read_parquet('{worker_data_path}/orders/orders.*.parquet') AS orders
       WHERE mod (abs (hash (o_custkey)), {overall_shard_count}) + 1 = {shard_id}
  - name: lineitem
    parent_table_name: orders
    query_template: |-
      SELECT * 
        FROM read_parquet('{worker_data_path}/lineitem/lineitem.*.parquet')
       WHERE l_orderkey IN (SELECT DISTINCT o_orderkey
                              FROM {parent_table_dataset}
                           )
  - name: customer
    parent_table_name: orders
    query_template: |-
      SELECT * 
        FROM read_parquet('{worker_data_path}/customer/customer.*.parquet') 
       WHERE c_custkey IN (SELECT DISTINCT o_custkey 
                             FROM {parent_table_dataset}
                          )
  - name: nation
    parent_table_name: ''
    query_template: |-
      SELECT *
        FROM read_parquet('{worker_data_path}/nation/nation.parquet')
  - name: part
    parent_table_name: lineitem
    query_template: |-
      SELECT *
        FROM read_parquet('{worker_data_path}/part/part.*.parquet')
       WHERE p_partkey IN (SELECT DISTINCT l_partkey 
                             FROM {parent_table_dataset}
                          )
  - name: region
    parent_table_name: ''
    query_template: |-
      SELECT *
        FROM read_parquet('{worker_data_path}/region/region.parquet')
  - name: partsupp
    parent_table_name: part
    query_template: |-
      SELECT *
        FROM read_parquet('{worker_data_path}/partsupp/partsupp.*.parquet')
       WHERE ps_partkey IN (SELECT DISTINCT p_partkey
                              FROM {parent_table_dataset}
                           )
  - name: supplier
    parent_table_name: partsupp
    query_template: |-
      SELECT *
        FROM read_parquet('{worker_data_path}/supplier/supplier.*.parquet') 
       WHERE s_suppkey IN (SELECT DISTINCT ps_suppkey 
                             FROM {parent_table_dataset}
                          )
