apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sidewinder.fullname" . }}-ebs-volume-claim
  annotations:
    "helm.sh/resource-policy": keep
spec:
  storageClassName: gp2
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
