apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sidewinder.fullname" . }}-efs-volume-claim
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Ti
