apiVersion: v1
kind: Secret
metadata:
  name: {{ include "src.fullname" . }}-secret
  labels:
    {{- include "src.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "secrets/*").AsSecrets | indent 2 }}
