apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sidewinder.fullname" . }}-local-volume-claim
  annotations:
    "helm.sh/resource-policy": keep
spec:
  storageClassName: local-storage
  volumeName: local-pv-c7d135bd # Change me to whatever the volume provisioner named the PV - this "pins" the server to one node
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
