apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sidewinder.fullname" . }}-local-volume-claim
  annotations:
    "helm.sh/resource-policy": keep
spec:
  storageClassName: local-storage
  volumeName: local-pv-11949880
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
