apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sidewinder.fullname" . }}-server
  labels:
    {{- include "sidewinder.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sidewinder.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/global-secret.yaml") . | sha256sum }}
        {{- with .Values.server.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "sidewinder.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: local-volume
          persistentVolumeClaim:
            claimName: {{ include "sidewinder.fullname" . }}-local-volume-claim
      {{- with .Values.server.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: [ "sh", "-c", "chmod -R 777 /data" ]
          volumeMounts:
            - name: local-volume
              mountPath: /data
      containers:
        - name: {{ .Chart.Name }}
          command: [ "/bin/bash" ]
          # args: [ "-c", "sleep infinity" ]
          args: [ "-c", "python -m server" ]
          volumeMounts:
            - name: local-volume
              mountPath: /home/app_user/data
          env:
            - name: SHARD_COUNT
              value: {{ .Values.server.config.shardCount | quote }}
            - name: DATABASE_FILE
              value: /home/app_user/data/tpch_{{ .Values.server.config.tpchScale }}.db
            - name: WORKER_DATA_PATH
              value: /home/app_user/data/tpch_{{ .Values.server.config.tpchScale }}
            - name: PING_TIMEOUT
              value: {{ .Values.server.config.pingTimeout | quote }}
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "sidewinder.fullname" . }}-secret
                  key: S3_ACCESS_KEY_ID
                  optional: false
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ include "sidewinder.fullname" . }}-secret
                  key: S3_REGION
                  optional: false
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "sidewinder.fullname" . }}-secret
                  key: S3_SECRET_ACCESS_KEY
                  optional: false
            - name: S3_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "sidewinder.fullname" . }}-secret
                  key: S3_SESSION_TOKEN
                  optional: false
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - name: websocket
              containerPort: 8765
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
