apiVersion: v1
kind: Service
metadata:
  name: {{ include "src.fullname" . }}
  labels:
    {{- include "src.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: websocket
      protocol: TCP
      name: websocket
  selector:
    {{- include "src.selectorLabels" . | nindent 4 }}
