apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "sidewinder.fullname" . }}-local-volume
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sidewinder.fullname" . }}-local-volume-claim
  annotations:
    "helm.sh/resource-policy": keep
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
