apiVersion: v1
kind: Service
metadata:
  name: {{ include "sidewinder.fullname" . }}
  labels:
    {{- include "sidewinder.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: websocket
      protocol: TCP
      name: websocket
  selector:
    {{- include "sidewinder.selectorLabels" . | nindent 4 }}
