apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sidewinder.fullname" . }}-tls-secret
  labels:
    {{- include "sidewinder.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "secrets/tls/*").AsSecrets | indent 2 }}
