apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sidewinder.fullname" . }}-worker-arm
  labels:
    {{- include "sidewinder.labels" . | nindent 4 }}
spec:
  replicas: 0 # {{ .Values.server.config.shardCount }}
  selector:
    matchLabels:
      {{- include "sidewinder.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/global-secret.yaml") . | sha256sum }}
        checksum/tls: {{ include (print $.Template.BasePath "/tls-secret.yaml") . | sha256sum }}
        {{- with .Values.worker.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "sidewinder.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.worker.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.worker.podSecurityContext | nindent 8 }}
      volumes:
        - name: nvme-volume
          hostPath:
            # directory location on host
            path: /nvme/disk
            # this field is optional
            type: Directory
        - name: tls-volume
          secret:
            secretName: {{ include "sidewinder.fullname" . }}-tls-secret
            optional: false
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: [ "sh", "-c", "chmod 777 /data" ]
          volumeMounts:
            - name: nvme-volume
              mountPath: /data
      containers:
        - name: {{ .Chart.Name }}
          volumeMounts:
            - name: nvme-volume
              mountPath: /tmp
            - name: tls-volume
              mountPath: /opt/sidewinder/tls/server.crt
              subPath: server.crt
              readOnly: true
          command: [ "/bin/bash" ]
          # args: [ "-c", "sleep infinity" ]
          args: [ "-c", "sidewinder-worker" ]
          env:
            - name: SERVER_HOSTNAME
              value: {{ include "sidewinder.fullname" . }}
            - name: WORKER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "sidewinder.fullname" . }}-secret
                  key: WORKER_USERNAME
                  optional: false
            - name: WORKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "sidewinder.fullname" . }}-secret
                  key: WORKER_PASSWORD
                  optional: false
            - name: TLS_VERIFY
              value: {{ .Values.client.config.tlsVerify | quote | default "TRUE" }}
          securityContext:
            {{- toYaml .Values.worker.securityContext | nindent 12 }}
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
#          ports:
#            - name: http
#              containerPort: 80
#              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
