apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sidewinder.fullname" . }}-worker
  labels:
    {{- include "sidewinder.labels" . | nindent 4 }}
spec:
  replicas: 0 # {{ .Values.server.config.shardCount }}
  selector:
    matchLabels:
      {{- include "sidewinder.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/global-secret.yaml") . | sha256sum }}
        {{- with .Values.worker.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "sidewinder.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: local-volume
          persistentVolumeClaim:
            claimName: {{ include "sidewinder.fullname" . }}-local-volume-claim
      {{- with .Values.worker.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.worker.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command: [ "/bin/bash" ]
          # args: [ "-c", "sleep infinity" ]
          args: [ "-c", "python -m worker" ]
          volumeMounts:
            - name: local-volume
              mountPath: /home/app_user/data
          env:
            - name: SERVER_URL
              value: ws://{{ include "sidewinder.fullname" . }}:{{ .Values.server.service.port }}/worker
            - name: LOAD_DUCKDB_S3_EXTENSION
              value: "False"
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "sidewinder.fullname" . }}-secret
                  key: S3_ACCESS_KEY_ID
                  optional: false
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ include "sidewinder.fullname" . }}-secret
                  key: S3_REGION
                  optional: false
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "sidewinder.fullname" . }}-secret
                  key: S3_SECRET_ACCESS_KEY
                  optional: false
            - name: S3_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "sidewinder.fullname" . }}-secret
                  key: S3_SESSION_TOKEN
                  optional: false
          securityContext:
            {{- toYaml .Values.worker.securityContext | nindent 12 }}
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
#          ports:
#            - name: http
#              containerPort: 80
#              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
